### PR TITLE
Data map example

### PR DESCRIPTION
**Pull request by kbjarkefur**
The DIME Wiki did not feel like the best place for a narrative example like this example.

It also did not feel like the best place to keep the master version of, for example, the data linkage template.

Let me know what you think!

### CODE REVIEW

**Comment by Avnish95** [comment]
Intro - suggested edit: 
This is an example of using a data map to organize workflow in a project. The mock data in this example is based on a typical impact evaluation project at DIME, but this framework should work on any research project that use data from more than one source.

**Comment by Avnish95** [comment]
Suggested edit for mock example background: 
Background
This example is based on a fictional agriculture impact evaluation project, that we will call ProjectIE. In ProjectIE, there are two types of data sources - data acquired by household surveys, and admin data shared by a government partner. Further, there are two units of observation - community and farmer. The intervention for this impact evaluation is a training that is offered to farmers in the treatment group. The treatment assignment was done randomly by clustering at the community level, so all the farmers in the same community have the same treatment assignment.

**Comment by Avnish95** [comment]
Suggested edit for "Notes on this data linkage table":
* In the table above, note that the farmer listing data has two IDs. Research projects usually have both project IDs, as well as a government ID. In this case, we need to list both these IDs, but a research project should not use an external ID if the dataset contains confidential information.
* Only list the raw datasets in this table and not derived datasets. However, make sure that your code clearly documents how derivative datasets relate to these datasets.
* If your raw datasets includes confidential information (such as PII), then this information must be encrypted. A benefit of the data linkage table is that it is also available to people that do not have access to the encrypted folder.
* Confidential information should always be encrypted by the project team when backing up project data. The only exception to this is if the data is either on an external hard drive which is locked up in a safe, or if your IT department has set up a secure sync service (see our guidelines for using the World Bank OneDrive here).

**Comment by kbjarkefur** [comment]
These are all great! I accepted with some minor edits

**Comment by Avnish95** [comment]
Suggested edits for Master Datasets: 
In ProjectIE, there are two units of observation in the data linkage table - community and farmer . Therefore, we need master datasets for each of these, and each master dataset should include all observations that the research team has ever interacted with. Note that due to this definition, the master datasets will often include more observations than are included in your analysis sample. For example, in ProjectIE, these additional observations could include farmers listed in the government partner's admin data that were selected to be a part of the sample. Similarly, there could be farmers who were not included in your study sample, but who treatment group training programs, and were therefore included in the monitoring data.

<-farmer master dataset->

The above table is an excerpt of a master dataset that lists all farmers with whom the research team for ProjectIE has ever interacted. Most (but not all) of these farmers are included in the sample for this study. Note that we have not included treatment status in this master dataset. As mentioned earlier, treatment status in this fictional study was randomly assigned at the community level, so treatment status will be included in the community master dataset (excerpt below). However, since sampling for this project was done at the farmer level, therefore sampling status has been included in this master dataset.

<- community master dataset ->

The above table is an excerpt of all the communities that are relevant for our example, that is, ProjectIE. Since treatment was randomly assigned at the community level, this master dataset is the authoritative source of information on treatment status, even though farmers will be the unit of analysis for regressions in this study.

Notes on these master data sets
* It is common to put the project ID as the leftmost columns, but note that the master dataset does not govern what the project ID is - that is governed by the data linkage table

Use master datasets to identify datasets without the project ID

If the research team receives a dataset without the project ID, then they must merge these datasets with the master dataset for the relevant unit of observation. For instance, suppose that our monitoring data was attendance sheets from the training sessions, but it does not have any other identifier except full names and the community where they live. Further, suppose that that we also want to merge treatment status with the monitoring data to see if anyone in the control group had attended the trainings. In this case, we would first have to merge the monitoring data with the farmer master dataset using a string match.

Please note that we have to resolve all ambiguous string matches manually to make sure that matches that are not exact are resolved correctly. Note that we will do this string match for all farmers in the farmer master dataset, and not just for the farmers we think might have attended (that is, farmers in the treatment group). In this case, including all farmers gives us the maximum amount of information for resolving any unambiguous matches.

If we find any farmers that we do not have in our farmer master dataset, then we should add them to the master dataset and assign them a project ID. For example, see farmer with ID 20751 in the farmer master dataset. This could be an example of a farmer who attended the training, but was not in the sample.

Once we have performed the string match as accurately as possible, we will have project IDs for both, farmers as well as the communities in the monitoring data. Then we can easily merge this with the community master dataset to get information on the treatment status.

**Comment by kbjarkefur** [comment]
Thanks @Avnish95 for these edits. I had missed that these were not merged yet, but your suggestions were great!

**Pull request merged**
